// AWS configuration using environment variables
// These values come from .env.local which is auto-generated by the deployment script

export const awsConfig = {
  Auth: {
    Cognito: {
      region: process.env.NEXT_PUBLIC_REGION,
      userPoolId: process.env.NEXT_PUBLIC_USER_POOL_ID || '',
      userPoolClientId: process.env.NEXT_PUBLIC_USER_POOL_CLIENT_ID || '',
      identityPoolId: process.env.NEXT_PUBLIC_IDENTITY_POOL_ID || '',
    },
  },
  API: {
    REST: {
      CortexAI: {
        endpoint: process.env.NEXT_PUBLIC_API_URL || '',
        region: process.env.NEXT_PUBLIC_REGION,
      },
    },
  },
  Storage: {
    S3: {
      bucket: process.env.NEXT_PUBLIC_BUCKET || '',
      region: process.env.NEXT_PUBLIC_REGION,
    },
  },
};

export default awsConfig;
